### ISSUE TITLE
PR 에서 code style 검사하는 Acctions 필요성 

### ISSUE THREAD

**Issue by BecomeWeasel** [Wander-Log/wanderlog#3]
ㅈㄱㄴ

**Comment by sjmin98** [comment]
https://github.com/SonarSource/sonarcloud-github-action

이런 기능 말씀하시는 걸까요?! 소나큐브를 github actions CI 과정에 연동해서 정적 코드 분석 진행하는 툴입니다!

@BecomeWeasel

**Comment by BecomeWeasel** [comment]
check [this](https://github.com/Wander-Log/wanderlog/pull/10)

**Comment by BecomeWeasel** [comment]
`./gradlew formatKotlin`
